spring.application.name=organicoffe-service

# Postgres
spring.datasource.url=jdbc:postgresql://45.151.123.19:5432/organicoffee
spring.datasource.username=postgres
spring.datasource.password=SaintsRowTheThird1900

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.show-sql=false

# HikariCP (pool)
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.pool-name=HikariPool-Organicoffe

# Server
server.port=8089

# (Opcional) logs de SQL/conn
# logging.level.org.hibernate.orm.connections.pooling=INFO
# logging.level.com.zaxxer.hikari=INFO
